[package]
name = "example game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = { git = "https://github.com/bevyengine/bevy", branch = "main", package = "bevy_ecs" }

bytemuck = "1.15.0"
glam = "0.27.0"
noise = "0.9.0"
puddle = {path = "../puddle/"}
rand = "0.8.5"

regex = "1.10.4"

