[package]
name = "example_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = { git = "https://github.com/bevyengine/bevy", branch = "main", package = "bevy_ecs" }
glam = "0.27.0"

image = "0.24.9"
noise = "0.9.0"
puddle = {path = "../puddle/"}

