[package]
name = "puddle"
version = "0.1.0"
edition = "2021"

[dependencies]
application = { path = "./crates/application" }
window = { path = "./crates/window" }
rendering = { path = "./crates/rendering" }
asset_manager = { path = "./crates/asset_manager" }
legion = "0.4.0"
