[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
application = { path = "../application" }
wgpu = "0.19.1"
window = { path = "../window" }
legion = "0.4.0"
texture = { path = "../texture" }
bytemuck = { version = "1.14.3", features = ["derive"] }
events = { path = "../events" }
cgmath = "0.18.0"
