[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
application = { path = "../application" }
window = { path = "../window" }
legion = "0.4.0"
bytemuck = {version = "1.15.0", features = ["derive"]}
regex = "1.10.4"
cgmath = "0.18.0"
vulkano = { git = "https://github.com/vulkano-rs/vulkano", branch = "master", features = ["macros"], default-features = false }
vulkano-shaders = "0.34.0"
