[package]
name = "time"
version = "0.1.0"
edition = "2021"

[dependencies]
application = {path = "../application"}
bevy_ecs = { git = "https://github.com/bevyengine/bevy", branch = "main", package = "bevy_ecs" }

